Add missing export macro to fix ASAN/UBSAN build
While building positioningquick:
qquickgeocoordinateanimation.cpp.o:(.data.rel+0x1338): undefined reference to `typeinfo for QGeoCoordinatePrivate'

Change-Id: I40eb3a33dddb338665da2b9982ffd5b871e7338e
Reviewed-by: Ivan Solovev <ivan.solovev@qt.io>
(cherry picked from commit 5ac409e067328689916877f301669153721edff7)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit 6981f0e88194c0c821ad7c4c97aeb18da4e2e442)
(cherry picked from commit 64c1093835a4ae6f38c4a6c340674e493ff938ae)