Add missing export macro to fix ASAN/UBSAN build
While building positioningquick:
qquickgeocoordinateanimation.cpp.o:(.data.rel+0x1338): undefined reference to `typeinfo for QGeoCoordinatePrivate'

Pick-to: 6.9 6.8 6.5
Change-Id: I40eb3a33dddb338665da2b9982ffd5b871e7338e
Reviewed-by: Ivan Solovev <ivan.solovev@qt.io>