ohos: fix build with llvm/clang 22 about missing initializer
src/plugins/position/ohos/qohosgeopositioninfosource.cpp:147:21: error: missing field 'optEventSourceAliveCheckFunc' initializer [-Werror,-Wmissing-designated-field-initializers]
  147 |                     }));
      |                     ^

Change-Id: I3396732332f7ed7ec64c050ea3e075e24fd064c7
Reviewed-by: SanthoshKumar Selvaraj <santhosh.kumar.selvaraj@qt.io>
(cherry picked from commit 0212b489ea33572e76cf2ecd41c76cc8370f8c8c)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>